export const _FakeIpLoc = {
  status: "success",
  country: "United Arab Emirates",
  countryCode: "AE",
  region: "FU",
  regionName: "Fujairah",
  city: "Al Fujairah City",
  zip: "",
  lat: 25.1288,
  lon: 56.3265,
  timezone: "Asia/Dubai",
  isp: "Global Internet Solutions LLC",
  org: "Global Internet Solutions LLC",
  as: "AS207713 GLOBAL INTERNET SOLUTIONS LLC",
  query: "5.44.42.104",
};